# -----------------------------------------------------------------------------
# Roomba in Python
# This file implements an algorithm for a roomba cleaning a room.
#
# Author: Dr. EB <------ REPLACE THIS WITH YOUR NAME!
# -----------------------------------------------------------------------------
 
from turtle import right, left, forward, backward, speed
import room

# THIS PARAMETER CAN CHANGE!!!
# Make sure your code works for n_alcoves = 0, 1, 2, 3, and 4
# (You are allowed to use this parameter in your code)
n_alcoves = 3

# Draw the Level 7 version of the room
window = room.draw_room(level = 7, n_alcoves = n_alcoves)

###
# Start your code here
speed(1000)

sq = 40


forward(sq) 
left(90)
forward(sq*3)
backward(sq*6)
right(90)
forward(sq*1)
right(90)
forward(sq*1)
backward(sq*8)
left(90)
forward(sq*1)
right(90)
forward(sq*8)
left(90)
forward(sq)
left(90)
forward(sq*8)
right(90)
forward(sq)
right(90)
backward(sq)
forward(sq*10)
backward(sq)
left(90)
forward(sq)
left(90)
forward(sq*8)
right(90)
forward(sq)
right(90)
forward(sq*8)
left(90)
forward(sq)
left(90)
forward(sq*8)
backward(sq)
right(90)
forward(sq)
left(90)
backward(sq*6)
forward(sq*3)
right(90)
forward(sq)

forward(sq*5)
backward(sq*3)
left(90)
def sqrfunc(spiral):
        forward(spiral)
        right(90)

sqrfunc(sq*6)
sqrfunc(sq*14)
sqrfunc(sq*12)
sqrfunc(sq*13)
sqrfunc(sq*13)
for i in range(2):
      sqrfunc(sq*14)
sqrfunc(sq*13)
sqrfunc(sq*15)
sqrfunc(sq*12)
sqrfunc(sq*16)
sqrfunc(sq*12)
sqrfunc(sq*16)
sqrfunc(sq*11)
sqrfunc(sq*13)
for i in range(2):
       sqrfunc(sq*10)
sqrfunc(sq*9)
sqrfunc(sq*14)
sqrfunc(sq*8)
sqrfunc(sq*18)
sqrfunc(sq*8)
sqrfunc(sq*18)
sqrfunc(sq*7)
sqrfunc(sq*15)
sqrfunc(sq*11)
sqrfunc(sq*13)
sqrfunc(sq*15)
sqrfunc(sq*11)
sqrfunc(sq*16)
sqrfunc(sq*8)
sqrfunc(sq*18)
sqrfunc(sq*7)
sqrfunc(sq*12)
sqrfunc(sq*9)
sqrfunc(sq*11)
sqrfunc(sq*8)
sqrfunc(sq*10)
sqrfunc(sq*5)
sqrfunc(sq*4)
sqrfunc(sq*4)
sqrfunc(sq*3)
sqrfunc(sq*3)
sqrfunc(sq*2)
sqrfunc(sq*2)
sqrfunc(sq)

forward(sq*10)
backward(sq*20)
forward(sq*10)
right(90)
forward(sq*10)
backward(sq*20)
forward(sq*10)

left(90)
forward(sq*20)

right(180)
forward(sq) 
left(90)
forward(sq*3)
backward(sq*6)
right(90)
forward(sq*1)
right(90)
forward(sq*1)
backward(sq*8)
left(90)
forward(sq*1)
right(90)
forward(sq*8)
left(90)
forward(sq)
left(90)
forward(sq*8)
right(90)
forward(sq)
right(90)
backward(sq)
forward(sq*10)
backward(sq)
left(90)
forward(sq)
left(90)
forward(sq*8)
right(90)
forward(sq)
right(90)
forward(sq*8)
left(90)
forward(sq)
left(90)
forward(sq*8)
backward(sq)
right(90)
forward(sq)
left(90)
backward(sq*6)
forward(sq*3)
right(90)
forward(sq)

forward(sq*30)
left(180)
forward(sq) 
left(90)
forward(sq*3)
backward(sq*6)
right(90)
forward(sq*1)
right(90)
forward(sq*1)
backward(sq*8)
left(90)
forward(sq*1)
right(90)
forward(sq*8)
left(90)
forward(sq)
left(90)
forward(sq*8)
right(90)
forward(sq)
right(90)
backward(sq)
forward(sq*10)
backward(sq)
left(90)
forward(sq)
left(90)
forward(sq*8)
right(90)
forward(sq)
right(90)
forward(sq*8)
left(90)
forward(sq)
left(90)
forward(sq*8)
backward(sq)
right(90)
forward(sq)
left(90)
backward(sq*6)
forward(sq*3)
right(90)
forward(sq)
###
 
window.exitonclick()